name: build
on:
  - push
  - pull_request
jobs:
  build:
    name: java v${{ matrix.java-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 17
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: gradle
      - run: ./gradlew check jacocoTestReport
      - uses: codecov/codecov-action@v3
